# Generated by Django 3.1.2 on 2020-11-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.ImageField(null=True, upload_to='my-photos/')),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pics.category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pics.areas')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
