# Generated by Django 3.1.2 on 2020-11-17 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pics',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
